//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_Practico___Programacion_Web_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PW3_20152C_TP2_TorneosEntities : DbContext
    {
        public PW3_20152C_TP2_TorneosEntities()
            : base("name=PW3_20152C_TP2_TorneosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contacto> Contacto { get; set; }
        public DbSet<Equipo> Equipo { get; set; }
        public DbSet<Jugador> Jugador { get; set; }
        public DbSet<Torneo> Torneo { get; set; }
    }
}
