//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_Practico___Programacion_Web_3
{
    using System;
    using System.Collections.Generic;

    public partial class Equipo
    {
        public Equipo()
        {
            this.Jugador = new HashSet<Jugador>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> MontoAbonado { get; set; }
        public Nullable<int> IdTorneo { get; set; }
    
        public virtual Torneo Torneo { get; set; }
        public virtual ICollection<Jugador> Jugador { get; set; }

        //public string ToJSON()
        //{
        //    System.Web.Script.Serialization.JavaScriptSerializer jsonSerializer = new System.Web.Script.Serialization.JavaScriptSerializer();
        //    return jsonSerializer.Serialize(this);
        //}
    }
}
